# These jobs are run on everything, including main and PRs.
name: Validate

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  XCODE_VERSION: "26.1"

jobs:
  lint:
    name: Lint
    timeout-minutes: 2
    runs-on: macos-26
    defaults:
      run:
        working-directory: ./Vault

    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer

      - name: Cache SPM Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm/repositories
            Vault/.build
          key: ${{ runner.os }}-spm-lint-${{ hashFiles('Vault/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-lint-

      - name: Check Linting & Formatting
        run: make lint

  # Don't test for now to save CI time
  # test:
  #   name: Test
  #   timeout-minutes: 10
  #   runs-on: macos-26
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
  #
  #     - name: Cache SPM Dependencies
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/Library/Caches/org.swift.swiftpm/repositories
  #         key: ${{ runner.os }}-spm-${{ hashFiles('Vault/Package.resolved') }}
  #         restore-keys: |
  #           ${{ runner.os }}-spm-
  #
  #     - name: Clear SPM Artifacts
  #       run: rm -rf ~/Library/Caches/org.swift.swiftpm/artifacts
  #
  #     - name: Test CI_macOS
  #       run: xcodebuild test -workspace Vault.xcworkspace -scheme CI_macOS -skipMacroValidation -skipPackagePluginValidation
